name: Generate and Commit GeoJSON

on:
  push:
    branches:
      - main  # or 'master', depending on your repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run GeoJSON generator
        run: python generate_geojson.py  # Replace with your actual script

      - name: Commit GeoJSON files if they exist
        run: |
          if ls output/*.geojson 1> /dev/null 2>&1; then
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add output/*.geojson
            git commit -m "Add/update generated GeoJSON files"
            git push
          else
            echo "No GeoJSON files to commit."
          fi
